// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD3O95F5HbnD6mTJzga7a0nHIYlLLSO0s',
    appId: '1:32487706662:web:4b7420fbe310d6e21ed6e7',
    messagingSenderId: '32487706662',
    projectId: 'firecrud-836f2',
    authDomain: 'firecrud-836f2.firebaseapp.com',
    storageBucket: 'firecrud-836f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDby2T0MKE8uASFkx_W345SAdyTDCNZbNs',
    appId: '1:32487706662:android:955c53291c0a79711ed6e7',
    messagingSenderId: '32487706662',
    projectId: 'firecrud-836f2',
    storageBucket: 'firecrud-836f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAza8edosJddUUfuC7w4XdV5BotRsnfrlM',
    appId: '1:32487706662:ios:693ff253f3fa54881ed6e7',
    messagingSenderId: '32487706662',
    projectId: 'firecrud-836f2',
    storageBucket: 'firecrud-836f2.appspot.com',
    iosClientId: '32487706662-fsk59748nfl7c28fgs5v8u9vm1mua4k3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter239320Firecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAza8edosJddUUfuC7w4XdV5BotRsnfrlM',
    appId: '1:32487706662:ios:693ff253f3fa54881ed6e7',
    messagingSenderId: '32487706662',
    projectId: 'firecrud-836f2',
    storageBucket: 'firecrud-836f2.appspot.com',
    iosClientId: '32487706662-fsk59748nfl7c28fgs5v8u9vm1mua4k3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutter239320Firecrud',
  );
}
